### ISSUE TITLE
Add help text for "submission set" field in Place Email Template

### ISSUE THREAD

**Issue by modulitos** [mapseed/api#96]
The "submission set" field should be "places", and eventually include other submission sets like "comments". We should add a help text to make this more clear. 

![api-submission-set](https://user-images.githubusercontent.com/4207017/32139885-14085c94-bc0c-11e7-9a68-f11282ef083f.png)

Eventually, it would be nice to have a proper foreign key relationship for our "submission set" fields, which are used in our permissions, datasets, and origins as well. But at least those fields include a section of help text to guide the user.

**Comment by jalMogo** [comment]
Addressed here: https://github.com/mapseed/api/pull/142
